name = "wormhole3-official-new"
compatibility_date = "2024-12-02"

# 告诉 Cloudflare 静态资源在这里
[assets]
directory = "./dist"
binding = "ASSETS"

# 如果使用 Worker 脚本处理路由，取消下面的注释
# main = "worker.js"
# routes = [
#   { pattern = "wormhole3.io/*", zone_name = "wormhole3.io" }
# ]

